services:

  backend:
    build:
      context: ./ttes-icg-sante
      dockerfile: Dockerfile

    container_name: ttes-icg-backend

    environment:
      SERVER_ADDRESS: 0.0.0.0
      SERVER_PORT: 8080

      SPRING_PROFILES_ACTIVE: prod

      SPRING_DATASOURCE_URL: ${SPRING_DATASOURCE_URL}
      SPRING_DATASOURCE_USERNAME: ${SPRING_DATASOURCE_USERNAME}
      SPRING_DATASOURCE_PASSWORD: ${SPRING_DATASOURCE_PASSWORD}

    ports:
      - "8080:8080"

    networks:
      - ttes-network

    restart: unless-stopped


  frontend:
    build:
      context: ./ttes-icg-sante-frontend
      dockerfile: Dockerfile

    container_name: ttes-icg-frontend

    depends_on:
      - backend

    ports:
      - "80:80"

    networks:
      - ttes-network

    restart: unless-stopped


networks:
  ttes-network:
    driver: bridge