services:

  postgres:
    image: postgres:17-alpine
    container_name: ttes-icg-postgres

    environment:
      POSTGRES_DB: ttes_icg_sante
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: AZERTY

    volumes:
      - postgres_data:/var/lib/postgresql/data

    networks:
      - ttes-network

    restart: unless-stopped

    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres -d ttes_icg_sante"]
      interval: 10s
      timeout: 5s
      retries: 5


  backend:
    build:
      context: ./ttes-icg-sante
      dockerfile: Dockerfile

    container_name: ttes-icg-backend

    depends_on:
      postgres:
        condition: service_healthy

    environment:
      SERVER_ADDRESS: 0.0.0.0
      SERVER_PORT: 8080

      SPRING_PROFILES_ACTIVE: prod

      SPRING_DATASOURCE_URL: jdbc:postgresql://postgres:5432/ttes_icg_sante
      SPRING_DATASOURCE_USERNAME: postgres
      SPRING_DATASOURCE_PASSWORD: AZERTY

    ports:
      - "8080:8080"

    networks:
      - ttes-network

    restart: unless-stopped


  frontend:
    build:
      context: ./ttes-icg-sante-frontend
      dockerfile: Dockerfile

    container_name: ttes-icg-frontend

    depends_on:
      - backend

    ports:
      - "80:80"

    networks:
      - ttes-network

    restart: unless-stopped


volumes:
  postgres_data:


networks:
  ttes-network:
    driver: bridge